### PR TITLE
fix: Only use Intel workaround for DG2

### LINKED ISSUE #14: DMABuf negotiation fails on Intel B580
```
$ GST_PLUGIN_PATH=./target/release/ GST_DEBUG=3 GST_GL_PLATFORM=egl gst-launch-1.0 waylanddisplaysrc ! "video/x-raw(memory:DMABuf),width=1920,height=1080,framerate=60/1" ! vapostproc ! vah264enc ! vah264dec ! glimagesink
2025-07-24T09:24:10.305133Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: []
2025-07-24T09:24:10.305165Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: []
2025-07-24T09:24:10.305190Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: []
2025-07-24T09:24:10.305212Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: []
2025-07-24T09:24:10.305253Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: []
Setting pipeline to PAUSED ...
2025-07-24T09:24:10.357309Z  INFO smithay::backend::egl::display: Successfully selected EGL platform: PLATFORM_DEVICE_EXT
2025-07-24T09:24:10.360695Z  INFO smithay::backend::egl::display: EGL Initialized
2025-07-24T09:24:10.360701Z  INFO smithay::backend::egl::display: EGL Version: (1, 5)
2025-07-24T09:24:10.360712Z  INFO smithay::backend::egl::display: Supported EGL display extensions: ["EGL_ANDROID_blob_cache", "EGL_ANDROID_native_fence_sync", "EGL_EXT_config_select_group", "EGL_EXT_create_context_robustness", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_EXT_query_reset_notification_strategy", "EGL_EXT_surface_compression", "EGL_IMG_context_priority", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_context_flush_control", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image_base", "EGL_KHR_no_config_context", "EGL_KHR_partial_update", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_gl_interop", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_MESA_x11_native_visual_id", "EGL_WL_bind_wayland_display", ""]
2025-07-24T09:24:10.363331Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}: smithay::backend::egl::context: EGL context created priority=Some(Medium)
2025-07-24T09:24:10.363993Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}:renderer_gles2: smithay::backend::renderer::gles: Initializing OpenGL ES Renderer
2025-07-24T09:24:10.363997Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}:renderer_gles2: smithay::backend::renderer::gles: GL Version: "OpenGL ES 3.2 Mesa 25.2.0-devel (git-fe3c1298dd)"
2025-07-24T09:24:10.364001Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}:renderer_gles2: smithay::backend::renderer::gles: GL Vendor: "Intel"
2025-07-24T09:24:10.364004Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}:renderer_gles2: smithay::backend::renderer::gles: GL Renderer: "Mesa Intel(R) Arc(tm) B580 Graphics (BMG G21)"
2025-07-24T09:24:10.364007Z  INFO egl{native="/dev/dri/renderD128" platform="PLATFORM_DEVICE_EXT" version=(1, 5)}:egl_context{ptr=139637373011712}:renderer_gles2: smithay::backend::renderer::gles: Supported GL Extensions: ["GL_EXT_blend_minmax", "GL_EXT_multi_draw_arrays", "GL_EXT_texture_filter_anisotropic", "GL_EXT_texture_compression_s3tc", "GL_EXT_texture_compression_dxt1", "GL_EXT_texture_compression_rgtc", "GL_EXT_texture_format_BGRA8888", "GL_OES_compressed_ETC1_RGB8_texture", "GL_OES_depth24", "GL_OES_element_index_uint", "GL_OES_fbo_render_mipmap", "GL_OES_mapbuffer", "GL_OES_rgb8_rgba8", "GL_OES_standard_derivatives", "GL_OES_stencil8", "GL_OES_texture_3D", "GL_OES_texture_float", "GL_OES_texture_float_linear", "GL_OES_texture_half_float", "GL_OES_texture_half_float_linear", "GL_OES_texture_npot", "GL_OES_vertex_half_float", "GL_EXT_draw_instanced", "GL_EXT_texture_sRGB_decode", "GL_OES_EGL_image", "GL_OES_depth_texture", "GL_AMD_performance_monitor", "GL_OES_packed_depth_stencil", "GL_EXT_texture_type_2_10_10_10_REV", "GL_NV_conditional_render", "GL_OES_get_program_binary", "GL_APPLE_texture_max_level", "GL_EXT_discard_framebuffer", "GL_EXT_read_format_bgra", "GL_EXT_texture_storage", "GL_NV_pack_subimage", "GL_NV_texture_barrier", "GL_EXT_frag_depth", "GL_NV_fbo_color_attachments", "GL_OES_EGL_image_external", "GL_OES_EGL_sync", "GL_OES_vertex_array_object", "GL_OES_viewport_array", "GL_ANGLE_pack_reverse_row_order", "GL_ANGLE_texture_compression_dxt3", "GL_ANGLE_texture_compression_dxt5", "GL_EXT_occlusion_query_boolean", "GL_EXT_robustness", "GL_EXT_texture_rg", "GL_EXT_unpack_subimage", "GL_NV_draw_buffers", "GL_NV_read_buffer", "GL_NV_read_depth", "GL_NV_read_depth_stencil", "GL_NV_read_stencil", "GL_APPLE_sync", "GL_EXT_draw_buffers", "GL_EXT_instanced_arrays", "GL_EXT_map_buffer_range", "GL_EXT_shadow_samplers", "GL_KHR_debug", "GL_KHR_robustness", "GL_KHR_texture_compression_astc_ldr", "GL_NV_generate_mipmap_sRGB", "GL_NV_pixel_buffer_object", "GL_OES_depth_texture_cube_map", "GL_OES_required_internalformat", "GL_OES_surfaceless_context", "GL_EXT_color_buffer_float", "GL_EXT_debug_label", "GL_EXT_sRGB_write_control", "GL_EXT_separate_shader_objects", "GL_EXT_shader_group_vote", "GL_EXT_shader_implicit_conversions", "GL_EXT_shader_integer_mix", "GL_EXT_tessellation_point_size", "GL_EXT_tessellation_shader", "GL_INTEL_conservative_rasterization", "GL_INTEL_performance_query", "GL_ANDROID_extension_pack_es31a", "GL_EXT_base_instance", "GL_EXT_compressed_ETC1_RGB8_sub_texture", "GL_EXT_copy_image", "GL_EXT_draw_buffers_indexed", "GL_EXT_draw_elements_base_vertex", "GL_EXT_gpu_shader5", "GL_EXT_multi_draw_indirect", "GL_EXT_polygon_offset_clamp", "GL_EXT_primitive_bounding_box", "GL_EXT_render_snorm", "GL_EXT_shader_io_blocks", "GL_EXT_texture_border_clamp", "GL_EXT_texture_buffer", "GL_EXT_texture_cube_map_array", "GL_EXT_texture_norm16", "GL_EXT_texture_view", "GL_KHR_blend_equation_advanced", "GL_KHR_context_flush_control", "GL_KHR_robust_buffer_access_behavior", "GL_NV_image_formats", "GL_NV_shader_noperspective_interpolation", "GL_OES_copy_image", "GL_OES_draw_buffers_indexed", "GL_OES_draw_elements_base_vertex", "GL_OES_gpu_shader5", "GL_OES_primitive_bounding_box", "GL_OES_sample_shading", "GL_OES_sample_variables", "GL_OES_shader_io_blocks", "GL_OES_shader_multisample_interpolation", "GL_OES_tessellation_point_size", "GL_OES_tessellation_shader", "GL_OES_texture_border_clamp", "GL_OES_texture_buffer", "GL_OES_texture_cube_map_array", "GL_OES_texture_stencil8", "GL_OES_texture_storage_multisample_2d_array", "GL_OES_texture_view", "GL_EXT_blend_func_extended", "GL_EXT_buffer_storage", "GL_EXT_float_blend", "GL_EXT_geometry_point_size", "GL_EXT_geometry_shader", "GL_EXT_shader_samples_identical", "GL_EXT_texture_sRGB_R8", "GL_KHR_no_error", "GL_KHR_texture_compression_astc_sliced_3d", "GL_NV_fragment_shader_interlock", "GL_OES_EGL_image_external_essl3", "GL_OES_geometry_point_size", "GL_OES_geometry_shader", "GL_OES_shader_image_atomic", "GL_EXT_clear_texture", "GL_EXT_clip_cull_distance", "GL_EXT_conservative_depth", "GL_EXT_disjoint_timer_query", "GL_EXT_texture_compression_s3tc_srgb", "GL_MESA_shader_integer_functions", "GL_EXT_clip_control", "GL_EXT_color_buffer_half_float", "GL_EXT_memory_object", "GL_EXT_memory_object_fd", "GL_EXT_semaphore", "GL_EXT_semaphore_fd", "GL_EXT_texture_compression_bptc", "GL_EXT_texture_mirror_clamp_to_edge", "GL_KHR_parallel_shader_compile", "GL_NV_alpha_to_coverage_dither_control", "GL_EXT_EGL_image_storage", "GL_EXT_shader_framebuffer_fetch_non_coherent", "GL_EXT_texture_shadow_lod", "GL_INTEL_blackhole_render", "GL_MESA_framebuffer_flip_y", "GL_NV_compute_shader_derivatives", "GL_EXT_demote_to_helper_invocation", "GL_EXT_depth_clamp", "GL_EXT_texture_query_lod", "GL_MESA_sampler_objects", "GL_EXT_EGL_image_storage_compression", "GL_EXT_texture_storage_compression", "GL_MESA_bgra", "GL_MESA_texture_const_bandwidth", ""]
2025-07-24T09:24:10.373825Z  INFO smithay::backend::libinput: Initializing a libinput backend
2025-07-24T09:24:10.373843Z  INFO input_seat{name="seat-0"}:add_keyboard{xkb_config=XkbConfig { rules: "", model: "", layout: "", variant: "", options: None } repeat_delay=200 repeat_rate=25}:input_keyboard: smithay::input::keyboard: Initializing a xkbcommon handler with keymap query
2025-07-24T09:24:10.375196Z  INFO input_seat{name="seat-0"}:add_keyboard{xkb_config=XkbConfig { rules: "", model: "", layout: "", variant: "", options: None } repeat_delay=200 repeat_rate=25}:input_keyboard: smithay::input::keyboard: Loaded Keymap name="English (US)"
2025-07-24T09:24:10.375498Z  INFO smithay::wayland::socket: Created new socket name=Some("wayland-1")
2025-07-24T09:24:10.375503Z  INFO waylanddisplaycore::comp: Listening on wayland socket. socket_name="wayland-1"
Pipeline is live and does not need PREROLL ...
0:00:00.314438090 149438 0x7effc0000b70 FIXME                default gstutils.c:4169:gst_element_decorate_stream_id_internal:<waylanddisplaysrc0> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Got context from element 'sink': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayX11\)\ gldisplayx11-0";
Got context from element 'vah264dec0': gst.va.display.handle=context, gst-display=(GstObject)"\(GstVaDisplayDrm\)\ vadisplaydrm3", description=(string)"Intel\(R\)\ Gen\ Graphics", path=(string)/dev/dri/renderD128;
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
2025-07-24T09:24:10.378168Z  INFO gstwaylanddisplaysrc::waylandsrc::imp: Supported DMA formats: ["AB4H", "AB4H:0x0100000000000001", "AB4H:0x0100000000000002", "AB4H:0x0100000000000011", "XB4H", "XB4H:0x0100000000000001", "XB4H:0x0100000000000002", "XB4H:0x0100000000000011", "AR30", "AR30:0x0100000000000001", "AR30:0x0100000000000002", "AR30:0x0100000000000011", "XR30", "XR30:0x0100000000000001", "XR30:0x0100000000000002", "XR30:0x0100000000000011", "AB30", "AB30:0x0100000000000001", "AB30:0x0100000000000002", "AB30:0x0100000000000011", "AR24", "AR24:0x0100000000000001", "AR24:0x0100000000000002", "AR24:0x0100000000000011", "AB24", "AB24:0x0100000000000001", "AB24:0x0100000000000002", "AB24:0x0100000000000011", "XR24", "XR24:0x0100000000000001", "XR24:0x0100000000000002", "XR24:0x0100000000000011", "XB24", "XB24:0x0100000000000001", "XB24:0x0100000000000002", "XB24:0x0100000000000011", "AR15", "AR15:0x0100000000000001", "AR15:0x0100000000000002", "AR15:0x0100000000000011", "RG16", "RG16:0x0100000000000001", "RG16:0x0100000000000002", "RG16:0x0100000000000011", "R8  ", "R8  :0x0100000000000001", "R8  :0x0100000000000002", "R8  :0x0100000000000011", "R16 ", "R16 :0x0100000000000001", "R16 :0x0100000000000002", "R16 :0x0100000000000011", "GR88", "GR88:0x0100000000000001", "GR88:0x0100000000000002", "GR88:0x0100000000000011", "GR32", "GR32:0x0100000000000001", "GR32:0x0100000000000002", "GR32:0x0100000000000011"]
0:00:00.317742539 149438 0x7effc0000b70 ERROR               GST_RUST base_src.rs:452:gstreamer_base::subclass::base_src::BaseSrcImplExt::parent_negotiate::{{closure}}:<waylanddisplaysrc0> Parent function `negotiate` failed
0:00:00.317753239 149438 0x7effc0000b70 WARN                 basesrc gstbasesrc.c:3187:gst_base_src_loop:<waylanddisplaysrc0> error: Internal data stream error.
0:00:00.317756816 149438 0x7effc0000b70 WARN                 basesrc gstbasesrc.c:3187:gst_base_src_loop:<waylanddisplaysrc0> error: streaming stopped, reason not-negotiated (-4)
ERROR: from element /GstPipeline:pipeline0/GstWaylandDisplaySrc:waylanddisplaysrc0: Internal data stream error.
Additional debug info:
../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c(3187): gst_base_src_loop (): /GstPipeline:pipeline0/GstWaylandDisplaySrc:waylanddisplaysrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.003195643
Setting pipeline to NULL ...
Freeing pipeline ...
```

```
$ gst-inspect-1.0 vapostproc
Factory Details:
  Rank                     none (0)
  Long-name                VA-API Video Postprocessor in Intel(R) Gen Graphics
  Klass                    Effect/Converter/Filter/Colorspace/Scaler/Video/Hardware
  Description              VA-API based video postprocessor
  Author                   Víctor Jáquez <vjaquez@igalia.com>
  Documentation            https://gstreamer.freedesktop.org/documentation/va/vapostproc.html

Plugin Details:
  Name                     va
  Description              VA-API codecs plugin
  Filename                 /usr/lib/gstreamer-1.0/libgstva.so
  Version                  1.26.4
  License                  LGPL
  Source module            gst-plugins-bad
  Documentation            https://gstreamer.freedesktop.org/documentation/va/
  Source release date      2025-07-16
  Binary package           Arch Linux GStreamer 1.26.4-1
  Origin URL               https://www.archlinux.org/

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstBaseTransform
                         +----GstVaBaseTransform
                               +----GstVaPostProc

Implemented Interfaces:
  GstColorBalance

Element Flags:

Pad Templates:
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      video/x-raw(memory:VAMemory)
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: { (string)NV12, (string)I420, (string)YV12, (string)YUY2, (string)Y42B, (string)RGBA, (string)BGRA, (string)RGBP, (string)RGBx, (string)P010_10LE, (string)RGB, (string)BGR10A2_LE, (string)VUYA, (string)Y210, (string)Y410 }
      video/x-raw(memory:DMABuf)
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: DMA_DRM
             drm-format: { (string)NV12:0x0100000000000009, (string)YU12, (string)YV12, (string)YUYV:0x0100000000000009, (string)YU16:0x0100000000000009, (string)AB24:0x0100000000000009, (string)AR24:0x0100000000000009, (string)XB24:0x0100000000000009, (string)P010:0x0100000000000009, (string)AR30:0x0100000000000009, (string)AYUV:0x0100000000000009, (string)Y210:0x0100000000000009, (string)Y410:0x0100000000000009 }
      video/x-raw
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: { (string)GRAY8, (string)P010_10LE, (string)Y210, (string)Y410, (string)I420, (string)BGR10A2_LE, (string)NV21, (string)P012_LE, (string)Y212_LE, (string)Y412_LE, (string)NV12, (string)YV12, (string)YUY2, (string)RGB16, (string)RGBA, (string)BGRA, (string)Y42B, (string)Y444, (string)RGBP, (string)VUYA, (string)RGBx, (string)BGRx, (string)UYVY }
  
  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-raw(memory:VAMemory)
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: { (string)NV12, (string)I420, (string)YV12, (string)YUY2, (string)Y42B, (string)RGBA, (string)BGRA, (string)RGBP, (string)RGBx, (string)P010_10LE, (string)RGB, (string)BGR10A2_LE, (string)VUYA, (string)Y210, (string)Y410 }
      video/x-raw(memory:DMABuf)
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: DMA_DRM
             drm-format: { (string)NV12:0x0100000000000009, (string)YU12, (string)YV12, (string)YUYV:0x0100000000000009, (string)YU16:0x0100000000000009, (string)AB24:0x0100000000000009, (string)AR24:0x0100000000000009, (string)XB24:0x0100000000000009, (string)P010:0x0100000000000009, (string)AR30:0x0100000000000009, (string)AYUV:0x0100000000000009, (string)Y210:0x0100000000000009, (string)Y410:0x0100000000000009 }
      video/x-raw
                  width: [ 16, 16384 ]
                 height: [ 16, 16384 ]
                 format: { (string)GRAY8, (string)P010_10LE, (string)Y210, (string)Y410, (string)I420, (string)BGR10A2_LE, (string)NV21, (string)P012_LE, (string)Y212_LE, (string)Y412_LE, (string)NV12, (string)YV12, (string)YUY2, (string)RGB16, (string)RGBA, (string)BGRA, (string)Y42B, (string)Y444, (string)RGBP, (string)VUYA, (string)RGBx, (string)BGRx, (string)UYVY }
```

### PR DESCRIPTION
**Pull request by DatCaptainHorse**
Took a bit, needed bit more than I thought.

Added mainly utilities for devices, with PCI vendor enums and Vulkan-based enumeration for GPUs.
New command to get the render device based on `state.render_node`, I thought about changing `RenderTarget` to use the new GPUDevice to make the enumeration-on-command unneeded, however I feel that's overreaching for a "fix" PR :sweat_smile: 

Draft initially as I reckon you might want some changes @ABeltramo ?

Should fix: #14

### CODE REVIEW

File: wayland-display-core/src/utils/device/gpu.rs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        {
+            primary_node
+        } else {
+            continue;
+        };
+
+        let properties = p_dev.properties();
+        let pci_vendor = PCIVendor::try_from(properties.vendor_id);
+        if pci_vendor.is_err() {
+            continue; // Skip unknown vendor
```
Comment (anonymix007) [inline wayland-display-core/src/utils/device/gpu.rs]: Is this a good idea? This will fail on i.e. devices with Qualcomm SoCs or RPi, though not sure how relevant are these

**Review by anonymix007 — COMMENTED** [review]
Seems to be working, nice!

File: wayland-display-core/src/utils/device/gpu.rs (hunk 1 above)
Comment (DatCaptainHorse) [reply wayland-display-core/src/utils/device/gpu.rs]: @ABeltramo anyone using any other GPU than one from the big 3?

Comment (DatCaptainHorse) [reply wayland-display-core/src/utils/device/gpu.rs]: Resolving, it will just be left as "Unknown" with the latest commit. So still allows devices to pass.

**Comment by ABeltramo** [comment]
Looks good to me! Nice work!
